# Generated by Django 5.1.3 on 2024-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('date', models.TextField(blank=True)),
                ('tiempo', models.TextField(blank=True)),
                ('contador1', models.IntegerField(default=0)),
                ('contador2', models.IntegerField(default=0)),
            ],
        ),
    ]
