# Generated by Django 5.1.3 on 2024-11-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
