# Generated by Django 5.1.3 on 2024-11-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date',
            field=models.TextField(blank=True),
        ),
    ]
