# Generated by Django 5.1.3 on 2024-11-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='admin',
            new_name='is_admin',
        ),
    ]
