# Generated by Django 5.1.3 on 2024-11-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='done',
            new_name='type',
        ),
    ]
