# Generated by Django 5.1.3 on 2024-11-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_is_admin_usuario_adm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='passw',
        ),
    ]
